services:
  cartblitz:
    build:
      context: ./cartblitz
    container_name: cartblitz
    ports:
      - "8080:8080"
    networks:
      - spring-net
    depends_on:
      - eureka-server
      - config-server
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=sqldocker
      - spring.cloud.config.uri=http://config-server:8070
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cartblitz
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  
  coupon:
    build:
      context: ./coupon
    container_name: coupon
    ports:
      - "8081:8081"
    networks:
      - spring-net
    depends_on:
      - eureka-server
      - config-server
    environment:
      - spring.cloud.config.uri=http://config-server:8070
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8070:8070"
    networks:
      - spring-net
    environment:
      - server.port=8070

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-net
    environment:
      - server.port=8761
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8071:8071"
    networks:
      - spring-net
    depends_on:
      - eureka-server
      - config-server
    environment:
      - spring.cloud.config.uri=http://config-server:8070
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cartblitz
      - MYSQL_PASSWORD=root
    volumes:
      - ./CartBlitz_DB:/docker-entrypoint-initdb.d/CartBlitz_DB
      - mysql_data:/var/lib/mysql
  
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - "9411:9411"
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  mysql_data: